### ISSUE TITLE
ENABLE_THREAD_SAFE_CHECKS Issue

### ISSUE THREAD

**Issue by simeonradivoev** [sebas77/Svelto.Common#18]
if you enable `ENABLE_THREAD_SAFE_CHECKS` this leads to compilation issues. Mainly that `SharedDictonary.test` isn't public.

**Comment by sebas77** [comment]
I'll check the define once possible, I assume it is not essential for production

**Comment by sebas77** [comment]
hey I forgot about this one, you shouldn't use ENABLE_THREAD_SAFE_CHECKS, it leads to nothing atm, It's a place holder.
